FROM rockylinux:9

RUN dnf install -y --setopt=tsflags=nodocs --allowerasing \
    python3 \
    python3-pip \
    python3-devel \
    createrepo_c \
    curl \
    gpg \
    git \
    ca-certificates \
    dnf-plugins-core \
    && dnf clean all

ENV UV_LINK_MODE=copy
RUN curl -LsSf https://astral.sh/uv/install.sh | sh
ENV PATH="/root/.local/bin:${PATH}"

WORKDIR /app

CMD ["bash"]